; generated by PrusaSlicer 2.7.4+darwin-arm64 on 2026-04-26 at 11:01:00 UTC
; thumbnail_QOI begin 32x32 456
; iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=
; thumbnail_QOI end
M73 P0 R63
G28 ; home all axes
G1 Z0.2 F720
G1 X110.4 Y110.2 E0.12
; filament used [mm] = 1234.5
; filament used [g] = 3.72
; layer_height = 0.20
; estimated printing time (normal mode) = 1h 2m 3s
