include: package:flutter_lints/flutter.yaml
linter:
  rules:
    public_member_api_docs: false
    constant_identifier_names: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
