import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:threed_print_cost_calculator/gcode_import/gcode_import_file_picker.dart';
import 'package:threed_print_cost_calculator/gcode_import/gcode_import_result.dart';
import 'package:threed_print_cost_calculator/gcode_import/gcode_import_service.dart';

void main() {
  test('parses valid gcode from streamed file path', () async {
    final dir = await Directory.systemTemp.createTemp(
      'gcode_import_service_test',
    );
    addTearDown(() async => dir.delete(recursive: true));

    final file = File('${dir.path}/benchy.gcode');
    await file.writeAsString('''
; generated by PrusaSlicer
; filament used [mm] = 1234.5
; total filament weight [g] = 12.3
; layer_height = 0.2
; TIME:120
G1 X10 Y10
''');

    final result = await const GCodeImportService().importPickedFile(
      GCodePickedFile(
        name: 'benchy.gcode',
        path: file.path,
        size: await file.length(),
      ),
    );

    expect(result.slicer, GCodeSlicer.prusaSlicer);
    expect(result.estimatedDuration, const Duration(seconds: 120));
    expect(result.filamentLengthMm, closeTo(1234.5, 0.0001));
    expect(result.filamentWeightG, closeTo(12.3, 0.0001));
    expect(result.layerHeightMm, closeTo(0.2, 0.0001));
  });

  test('handles malformed utf8 from path without throwing', () async {
    final dir = await Directory.systemTemp.createTemp(
      'gcode_import_service_test',
    );
    addTearDown(() async => dir.delete(recursive: true));

    final file = File('${dir.path}/broken.stl');
    await file.writeAsBytes(Uint8List.fromList([0xFF, 0xFE, 0x41, 0x42]));

    final result = await const GCodeImportService().importPickedFile(
      GCodePickedFile(
        name: 'broken.stl',
        path: file.path,
        size: await file.length(),
      ),
    );

    expect(result.slicer, GCodeSlicer.unknown);
    expect(result.estimatedDuration, isNull);
    expect(result.filamentLengthMm, isNull);
    expect(result.filamentWeightG, isNull);
    expect(result.layerHeightMm, isNull);
    expect(result.hasAnyExtractedMetadata, isFalse);
  });
}
