import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:threed_print_cost_calculator/gcode_import/gcode_import_parser.dart';
import 'package:threed_print_cost_calculator/gcode_import/gcode_import_result.dart';

void main() {
  const parser = GCodeImportParser();
  final fixtures = '${Directory.current.path}/test/fixtures/gcode';
  String load(String name) => File('$fixtures/$name').readAsStringSync();

  group('GCodeImportParser', () {
    test('parses documented PrusaSlicer metadata', () {
      final result = parser.parse(load('prusa_slicer_basic.gcode'));

      expect(result.slicer, GCodeSlicer.prusaSlicer);
      expect(
        result.estimatedDuration,
        const Duration(hours: 1, minutes: 2, seconds: 3),
      );
      expect(result.filamentLengthMm, 1234.5);
      expect(result.filamentWeightG, 3.72);
      expect(result.layerHeightMm, 0.2);
      expect(result.previewMetadata?.present, isTrue);
      expect(result.previewMetadata?.format, 'QOI');
      expect(result.previewMetadata?.width, 32);
      expect(result.previewMetadata?.height, 32);
      expect(result.hasPreview, isTrue);
      expect(result.previewWidth, 32);
      expect(result.previewHeight, 32);
      expect(result.previewImageBytes, isNotNull);
      expect(result.warnings, isEmpty);
    });

    test('handles mixed totals and warns', () {
      final result = parser.parse(load('mixed_materials.gcode'));

      expect(result.filamentLengthMm, 300);
      expect(result.filamentWeightG, 4.0);
      expect(
        result.warnings.map((warning) => warning.code),
        contains(GCodeParseWarningCode.mixedMaterials),
      );
    });

    test('keeps filament when duration missing', () {
      final result = parser.parse(load('missing_duration_with_filament.gcode'));

      expect(result.estimatedDuration, isNull);
      expect(result.filamentLengthMm, 2500);
      expect(
        result.warnings.map((warning) => warning.code),
        contains(GCodeParseWarningCode.missingDuration),
      );
    });

    test('keeps duration when filament missing', () {
      final result = parser.parse(load('missing_filament_with_duration.gcode'));

      expect(result.estimatedDuration, const Duration(seconds: 900));
      expect(result.filamentLengthMm, isNull);
      expect(
        result.warnings.map((warning) => warning.code),
        contains(GCodeParseWarningCode.missingFilament),
      );
    });

    test('parses OrcaSlicer cura-style length metadata', () {
      final result = parser.parse(load('orca_slicer_basic.gcode'));

      expect(result.slicer, GCodeSlicer.orcaSlicer);
      expect(result.estimatedDuration, const Duration(seconds: 3709));
      expect(result.filamentLengthMm, closeTo(70.0, 0.001));
      expect(result.filamentWeightG, isNull);
      expect(result.layerHeightMm, 0.24);
      expect(
        result.warnings.map((warning) => warning.code),
        contains(GCodeParseWarningCode.missingFilamentWeight),
      );
    });

    test('parses documented Bambu Studio totals', () {
      final result = parser.parse(load('bambu_studio_basic.gcode'));

      expect(result.slicer, GCodeSlicer.bambuStudio);
      expect(
        result.estimatedDuration,
        const Duration(hours: 1, minutes: 10, seconds: 5),
      );
      expect(result.filamentLengthMm, 4321);
      expect(result.filamentWeightG, 12.34);
      expect(result.layerHeightMm, 0.16);
      expect(result.warnings, isEmpty);
    });

    test('parses Cura seconds and metre-based filament', () {
      final result = parser.parse(load('cura_basic.gcode'));

      expect(result.slicer, GCodeSlicer.cura);
      expect(result.estimatedDuration, const Duration(seconds: 626));
      expect(result.filamentLengthMm, closeTo(111.376, 0.001));
      expect(result.layerHeightMm, 0.1);
      expect(
        result.warnings.map((warning) => warning.code),
        contains(GCodeParseWarningCode.missingFilamentWeight),
      );
    });

    test('parses centimeter filament metadata', () {
      final result = parser.parse('''
; generated by test tool 2.1
; filament used [cm] = 12.5
''');

      expect(result.filamentLengthMm, 125);
    });

    test('parses multi-value centimeter filament metadata', () {
      final result = parser.parse('''
; generated by test tool 2.1
; filament used [cm] = 1cm, 2cm, 3cm
''');

      expect(result.filamentLengthMm, 60);
    });

    test('parses meter filament metadata', () {
      final result = parser.parse('''
; generated by test tool 2.1
; filament used [m] = 0.42
''');

      expect(result.filamentLengthMm, 420);
    });

    test('parses multi-value meter filament metadata', () {
      final result = parser.parse('''
; generated by test tool 2.1
; filament used [m] = 1m, 20cm, 300mm
''');

      expect(result.filamentLengthMm, 1500);
    });

    test('parses named duration from streamed lines', () async {
      final result = await parser.parseLineStream(
        Stream.fromIterable([
          '; generated by test tool 2.1',
          '; TIME: 1h 2m 3s',
          '; layer_height = 0.2',
        ]),
      );

      expect(
        result.estimatedDuration,
        const Duration(hours: 1, minutes: 2, seconds: 3),
      );
      expect(result.layerHeightMm, 0.2);
      expect(result.slicer, GCodeSlicer.unknown);
      expect(
        result.warnings.map((warning) => warning.code),
        contains(GCodeParseWarningCode.unknownSlicer),
      );
    });

    test('flags partial metadata when only some values exist', () {
      final result = parser.parse('''
; generated by test tool 2.1
; TIME: 900
; layer_height = 0.2
''');

      expect(result.estimatedDuration, const Duration(seconds: 900));
      expect(result.layerHeightMm, 0.2);
      expect(
        result.warnings.map((warning) => warning.code),
        contains(GCodeParseWarningCode.partialMetadata),
      );
    });

    test('keeps unknown slicer while extracting partial metadata', () {
      final result = parser.parse(load('unknown_basic.gcode'));

      expect(result.slicer, GCodeSlicer.unknown);
      expect(result.estimatedDuration, const Duration(minutes: 10));
      expect(result.filamentWeightG, 8.5);
      expect(
        result.warnings.map((warning) => warning.code),
        contains(GCodeParseWarningCode.unknownSlicer),
      );
    });

    test('reports missing metadata fixture warnings', () {
      final result = parser.parse(load('missing_metadata.gcode'));

      expect(result.slicer, GCodeSlicer.unknown);
      expect(result.estimatedDuration, isNull);
      expect(result.filamentLengthMm, isNull);
      expect(result.filamentWeightG, isNull);
      expect(result.previewMetadata, isNull);
      expect(
        result.warnings.map((warning) => warning.code),
        containsAll([
          GCodeParseWarningCode.unknownSlicer,
          GCodeParseWarningCode.missingDuration,
          GCodeParseWarningCode.missingFilament,
        ]),
      );
    });

    test('falls back from unsafe preview metadata', () {
      final result = parser.parse(load('unsafe_preview.gcode'));

      expect(result.previewMetadata?.present, isTrue);
      expect(result.hasSafePreview, isFalse);
    });
  });
}
