#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export PATH="/opt/homebrew/bin:$PATH"

fvm dart format lib test integration_test patrol_test test_support --set-exit-if-changed && fvm flutter analyze
